/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefreshRouteImport } from './routes/refresh'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AskFredaRouteImport } from './routes/ask-freda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const RefreshRoute = RefreshRouteImport.update({
  id: '/refresh',
  path: '/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AskFredaRoute = AskFredaRouteImport.update({
  id: '/ask-freda',
  path: '/ask-freda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ask-freda': typeof AskFredaRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/refresh': typeof RefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ask-freda': typeof AskFredaRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/refresh': typeof RefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ask-freda': typeof AskFredaRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/refresh': typeof RefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ask-freda'
    | '/login'
    | '/monitoring'
    | '/refresh'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/ask-freda' | '/login' | '/monitoring' | '/refresh'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ask-freda'
    | '/login'
    | '/monitoring'
    | '/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AskFredaRoute: typeof AskFredaRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  RefreshRoute: typeof RefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/refresh': {
      id: '/refresh'
      path: '/refresh'
      fullPath: '/refresh'
      preLoaderRoute: typeof RefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-freda': {
      id: '/ask-freda'
      path: '/ask-freda'
      fullPath: '/ask-freda'
      preLoaderRoute: typeof AskFredaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AskFredaRoute: AskFredaRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  RefreshRoute: RefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
