/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as SiteSpecificRouteImport } from './routes/site-specific'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ExportRouteImport } from './routes/export'
import { Route as AnySiteRouteImport } from './routes/any-site'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSpecificRoute = SiteSpecificRouteImport.update({
  id: '/site-specific',
  path: '/site-specific',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AnySiteRoute = AnySiteRouteImport.update({
  id: '/any-site',
  path: '/any-site',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/any-site': typeof AnySiteRoute
  '/export': typeof ExportRoute
  '/library': typeof LibraryRoute
  '/monitoring': typeof MonitoringRoute
  '/review': typeof ReviewRoute
  '/site-specific': typeof SiteSpecificRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/any-site': typeof AnySiteRoute
  '/export': typeof ExportRoute
  '/library': typeof LibraryRoute
  '/monitoring': typeof MonitoringRoute
  '/review': typeof ReviewRoute
  '/site-specific': typeof SiteSpecificRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/any-site': typeof AnySiteRoute
  '/export': typeof ExportRoute
  '/library': typeof LibraryRoute
  '/monitoring': typeof MonitoringRoute
  '/review': typeof ReviewRoute
  '/site-specific': typeof SiteSpecificRoute
  '/workflows': typeof WorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/any-site'
    | '/export'
    | '/library'
    | '/monitoring'
    | '/review'
    | '/site-specific'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/any-site'
    | '/export'
    | '/library'
    | '/monitoring'
    | '/review'
    | '/site-specific'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/any-site'
    | '/export'
    | '/library'
    | '/monitoring'
    | '/review'
    | '/site-specific'
    | '/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnySiteRoute: typeof AnySiteRoute
  ExportRoute: typeof ExportRoute
  LibraryRoute: typeof LibraryRoute
  MonitoringRoute: typeof MonitoringRoute
  ReviewRoute: typeof ReviewRoute
  SiteSpecificRoute: typeof SiteSpecificRoute
  WorkflowsRoute: typeof WorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-specific': {
      id: '/site-specific'
      path: '/site-specific'
      fullPath: '/site-specific'
      preLoaderRoute: typeof SiteSpecificRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/any-site': {
      id: '/any-site'
      path: '/any-site'
      fullPath: '/any-site'
      preLoaderRoute: typeof AnySiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnySiteRoute: AnySiteRoute,
  ExportRoute: ExportRoute,
  LibraryRoute: LibraryRoute,
  MonitoringRoute: MonitoringRoute,
  ReviewRoute: ReviewRoute,
  SiteSpecificRoute: SiteSpecificRoute,
  WorkflowsRoute: WorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
