/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminAccessRouteImport } from './routes/admin-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as PlaybooksRouteImport } from './routes/playbooks'
import { Route as RefreshRouteImport } from './routes/refresh'
import { Route as PlaybooksIndexRouteImport } from './routes/playbooks.index'
import { Route as PlaybooksAgentsRouteImport } from './routes/playbooks.agents'
import { Route as PlaybooksSolutionsRouteImport } from './routes/playbooks.solutions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/admin-access',
  path: '/admin-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksRoute = PlaybooksRouteImport.update({
  id: '/playbooks',
  path: '/playbooks',
  getParentRoute: () => rootRouteImport,
} as any)
const RefreshRoute = RefreshRouteImport.update({
  id: '/refresh',
  path: '/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybooksIndexRoute = PlaybooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaybooksRoute,
} as any)
const PlaybooksAgentsRoute = PlaybooksAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => PlaybooksRoute,
} as any)
const PlaybooksSolutionsRoute = PlaybooksSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => PlaybooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-access': typeof AdminAccessRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/playbooks': typeof PlaybooksRouteWithChildren
  '/refresh': typeof RefreshRoute
  '/playbooks/agents': typeof PlaybooksAgentsRoute
  '/playbooks/solutions': typeof PlaybooksSolutionsRoute
  '/playbooks/': typeof PlaybooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-access': typeof AdminAccessRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/refresh': typeof RefreshRoute
  '/playbooks/agents': typeof PlaybooksAgentsRoute
  '/playbooks/solutions': typeof PlaybooksSolutionsRoute
  '/playbooks': typeof PlaybooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-access': typeof AdminAccessRoute
  '/login': typeof LoginRoute
  '/monitoring': typeof MonitoringRoute
  '/playbooks': typeof PlaybooksRouteWithChildren
  '/refresh': typeof RefreshRoute
  '/playbooks/agents': typeof PlaybooksAgentsRoute
  '/playbooks/solutions': typeof PlaybooksSolutionsRoute
  '/playbooks/': typeof PlaybooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-access'
    | '/login'
    | '/monitoring'
    | '/playbooks'
    | '/refresh'
    | '/playbooks/agents'
    | '/playbooks/solutions'
    | '/playbooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-access'
    | '/login'
    | '/monitoring'
    | '/refresh'
    | '/playbooks/agents'
    | '/playbooks/solutions'
    | '/playbooks'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-access'
    | '/login'
    | '/monitoring'
    | '/playbooks'
    | '/refresh'
    | '/playbooks/agents'
    | '/playbooks/solutions'
    | '/playbooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminAccessRoute: typeof AdminAccessRoute
  LoginRoute: typeof LoginRoute
  MonitoringRoute: typeof MonitoringRoute
  PlaybooksRoute: typeof PlaybooksRouteWithChildren
  RefreshRoute: typeof RefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-access': {
      id: '/admin-access'
      path: '/admin-access'
      fullPath: '/admin-access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks': {
      id: '/playbooks'
      path: '/playbooks'
      fullPath: '/playbooks'
      preLoaderRoute: typeof PlaybooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refresh': {
      id: '/refresh'
      path: '/refresh'
      fullPath: '/refresh'
      preLoaderRoute: typeof RefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbooks/': {
      id: '/playbooks/'
      path: '/'
      fullPath: '/playbooks/'
      preLoaderRoute: typeof PlaybooksIndexRouteImport
      parentRoute: typeof PlaybooksRoute
    }
    '/playbooks/agents': {
      id: '/playbooks/agents'
      path: '/agents'
      fullPath: '/playbooks/agents'
      preLoaderRoute: typeof PlaybooksAgentsRouteImport
      parentRoute: typeof PlaybooksRoute
    }
    '/playbooks/solutions': {
      id: '/playbooks/solutions'
      path: '/solutions'
      fullPath: '/playbooks/solutions'
      preLoaderRoute: typeof PlaybooksSolutionsRouteImport
      parentRoute: typeof PlaybooksRoute
    }
  }
}

interface PlaybooksRouteChildren {
  PlaybooksAgentsRoute: typeof PlaybooksAgentsRoute
  PlaybooksSolutionsRoute: typeof PlaybooksSolutionsRoute
  PlaybooksIndexRoute: typeof PlaybooksIndexRoute
}

const PlaybooksRouteChildren: PlaybooksRouteChildren = {
  PlaybooksAgentsRoute: PlaybooksAgentsRoute,
  PlaybooksSolutionsRoute: PlaybooksSolutionsRoute,
  PlaybooksIndexRoute: PlaybooksIndexRoute,
}

const PlaybooksRouteWithChildren = PlaybooksRoute._addFileChildren(
  PlaybooksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminAccessRoute: AdminAccessRoute,
  LoginRoute: LoginRoute,
  MonitoringRoute: MonitoringRoute,
  PlaybooksRoute: PlaybooksRouteWithChildren,
  RefreshRoute: RefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
